[build]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y libsecret-1-dev:$CROSS_DEB_ARCH",
]

[build.env]
passthrough = [
    "PKG_CONFIG_SYSROOT_DIR",
    "PKG_CONFIG_PATH",
    "RUSTFLAGS"
]

[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main"

[target.armv7-unknown-linux-gnueabihf]
# needed to grab gcc (should be able to avoid using zig here, too)
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH && apt-get update",
    "DEBIAN_FRONTEND=noninteractive apt-get install libsecret-1-dev:armhf gcc-arm-linux-gnueabihf -y"
]
image = "ghcr.io/cross-rs/armv7-unknown-linux-gnueabihf:main"

[target.i686-unknown-linux-gnu]
# needed because i686 gcc is required to succeed
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH && apt-get update",
    "DEBIAN_FRONTEND=noninteractive apt-get install gcc-i686-linux-gnu libsecret-1-dev:i386 -y"
]
image = "ghcr.io/cross-rs/i686-unknown-linux-gnu:main"

[target.x86_64-unknown-linux-gnu]
pre-build = [
    "apt-get update",
    "DEBIAN_FRONTEND=noninteractive apt-get install libsecret-1-dev -y",
]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main"

[target.x86_64-unknown-linux-musl]
pre-build = [
    "apk add libsecret-dev musl-dev",
]
image = "amd64/rust:alpine"
