[target.aarch64-unknown-linux-gnu]
pre-build = ["dpkg --add-architecture arm64 && apt-get update && apt-get install libsecret-1-dev:arm64 -y"]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main"

[target.aarch64-unknown-linux-musl]
pre-build = ["dpkg --add-architecture arm64 && apt-get update && apt-get install libsecret-1-dev:arm64 -y"]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-musl:main"

[target.armv7-unknown-linux-gnueabihf]
pre-build = ["dpkg --add-architecture armhf && apt-get update && apt-get install libsecret-1-dev:armhf -y"]
image = "ghcr.io/cross-rs/armv7-unknown-linux-gnueabihf:main"

[target.i686-unknown-linux-gnu]
pre-build = ["dpkg --add-architecture i386 && apt-get update && apt-get install libsecret-1-dev:i386 -y"]
image = "ghcr.io/cross-rs/i686-unknown-linux-gnu:main"

[target.x86_64-unknown-linux-gnu]
pre-build = ["apt-get update && apt-get install libsecret-1-dev -y"]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main"

[target.x86_64-unknown-linux-musl]
pre-build = ["apt-get update && apt-get install libsecret-1-dev -y"]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-musl:main"
