/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function setPassword(service: string, account: string, password: string): Promise<boolean>
export function getPassword(service: string, account: string): Promise<string>
