/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Credential {
  username: string
  password: string
}
export function deletePassword(service: string, account: string): Promise<boolean>
export function findCredentials(service: string): Promise<unknown[]>
export function getPassword(service: string, account: string): Promise<string>
export function setPassword(service: string, account: string, password: string): Promise<boolean>
