name: CI
env:
  DEBUG: napi:*
  APP_NAME: keytar-rs
  MACOSX_DEPLOYMENT_TARGET: '10.13'
'on':
  push:
    branches:
      - '**'
    paths-ignore:
      - '**/*.md'
      - LICENSE
      - '**/*.gitignore'
      - .editorconfig
      - docs/**
  pull_request: null
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target: [
            'aarch64-unknown-linux-gnu',
            'aarch64-unknown-linux-musl',
            'armv7-unknown-linux-gnueabihf',
            'i686-unknown-linux-gnu',
            'x86_64-unknown-linux-gnu',
            'x86-64-unknown-linux-musl'
        ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo install cross
      - run: cross build --target ${{ matrix.target }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bindings-${{ matrix.settings.target }}
          path: ${{ env.APP_NAME }}.*.node
          if-no-files-found: error
